server:
  port: 8801
spring:
  application:
    name: cloud-stream-provider
  cloud:
    kafka:
      binder:
        brokers: 192.168.25.128:9092         #Kafka的消息中间件服务器
        zk-nodes: 192.168.25.128:2181        #Zookeeper的节点，如果集群，后面加,号分隔
        auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
      bindings:
        output:      #这里用stream给我们提供的默认output，后面会讲到自定义output
          destination: stream-demo    #消息发往的目的地
          content-type: application/json    #消息发送的格式，接收端不用指定格式，但是发送端要

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: streamProvider8801
    prefer-ip-address: true