server:
  port: 8888
spring:
  application:
    name: cloud-online-markdown

  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:file:~/.h2/editor
    username: sa
    password:
    schema:
      - classpath:/db/h2/schema.sql
    platform: h2
    initialization-mode: always
  #    hikari:
#      minimum-idle: 5
#      idle-timeout: 600000
#      maximum-pool-size: 10
#      auto-commit: true
#      pool-name: MyHikariCP
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapper-locations: classpath:mapper/*.xml
