server:
  port: 8888
spring:
  application:
    name: cloud-oauth2-server

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://106.14.200.232:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  security:
    user:
      name: admin
      password: 123456
#  cloud:
#    consul:
#      discovery:
#        host: 192.168.25.128
#        port: 8500
#        # 启用服务发现
#        enabled: true
#        # 启用服务注册
#        register: true
#        # 服务停止时取消注册
#        deregister: true
#        # 表示注册时使用IP而不是hostname
#        prefer-ip-address: true
#        # 执行监控检查的频率
#        health-check-interval: 30s
#        # 设置健康检查失败多长时间后，取消注册
#        health-check-critical-timeout: 30s
#        # 健康检查的路径
#        health-check-path: /actuator/info
#        # 服务注册标识，格式为：应用名称+服务器IP+端口
#        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
mybatis:
  mapper-locations: classpath:mapper/*.xml
