server:
  port: 80
spring:
  application:
    name: cloud-order-service
  cloud:
    zookeeper:
      connect-string: 192.168.25.128:2181

payment-service:
  url: http://cloud-payment-service/payment
