server:
  port: 8004
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.25.128:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  cloud:
    zookeeper:
      connect-string: 192.168.25.128:2181

mybatis:
  mapper-locations: classpath:mapper/*.xml
